#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory
makeType=${1:-libso}
set -x

compressible/Allwmake $*
incompressible/Allwmake $*

# ----------------------------------------------------------------- end-of-file
